shallow_clone: true

environment:
  matrix:
  - TOOLSET: vs2008
  - TOOLSET: vs2010
  - TOOLSET: vs2012
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - Debug
  - Release

install:
  - git clone https://github.com/bkaradzic/bx ..\bx
  - ..\bx\tools\bin\windows\genie --with-tools %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bgfx.sln
